### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/cli#13]
Should we create a log helper so strategies can log debug/info/error/warning messages? Debug messages are not very useful when all operations are successful, but when a plugin does not work after being imported the user may want to turn on the debug mode, in which all messages of all strategies are outputted

cc @martonsagi

**Comment by martonsagi** [comment]
How about using [aurelia-logging-console](https://github.com/aurelia/logging-console) [[docs]](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/10)?
> This library can be used in the browser as well as on the **server**.

It could be used to replace my silly logger function [here](https://github.com/monterey-framework/cli/blob/feat/import/lib/importer/import-default.js#L282).

* We would use `info` level by default, so custom importer would be able to send non-debug notifications to the user
* `--debug` switch would change log level to `debug` to show full details
* `--quiet` switch would change log level to `none` (and it would use default answers for questions with multiple choices)

**Comment by adriatic** [comment]
Seems like a logical choice, that would be liked by Rob 😏 . @JeroenVinke did you have something specific in mind, that is different from @martonsagi's proposal?

**Comment by JeroenVinke** [comment]
> Seems like a logical choice, that would be liked by Rob 😏 . @JeroenVinke did you have something specific in mind, that is different from @martonsagi's proposal?

Nope, but since aurelia-cli has so [few dependencies](https://github.com/monterey-framework/cli/blob/master/package.json#L26-L30) (before we started working on it), we may receive feedback to replace these additional dependencies with a custom solution when we open the PR

**Comment by adriatic** [comment]
Perhaps - but I would deal with it when it happens, optimizing the time to delivery rather than the number of dependencies 😄.`aurelia-cli` is a command line executable application and its size seems pretty irelevant, as it is dwarfed by npm.exe for example

**Comment by martonsagi** [comment]
In my opinion `aurelia-logging-console` can't be considered a third-party dependency, and it's high likely that this package will already be installed regardless of build environment. 

For example [skeletons](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext-aspnetcore/src/skeleton/package.json#L77) declare it as a dependency.

**Comment by EisenbergEffect** [comment]
Using any aurelia lib is fine. We are mainly being careful of libs we
cannot control.
