### ISSUE TITLE
Create package installer abstraction (and npm/yarn implementations)

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/cli#2]
![image](https://cloud.githubusercontent.com/assets/2189477/20866775/49c88e3c-ba35-11e6-9452-b5fb316e4b8d.png)

For the `au install` command we need to have an abstraction for installing plugins (not configuring plugins). For now we can add `npm` and [`yarn`](https://github.com/yarnpkg/yarn)

**Question:** How do we configure defaults for which package manager to use? Does the user need to use a flag when calling `au install`, such as `au install --yarn` ?

**Comment by EisenbergEffect** [comment]
I think we should add a `packageManager` property to the aurelia.json file. That would allow us to tell which to use. If this value isn't present, we can just assume npm. Future version so the CLI could configure this explicitly and even ask the end user what their preference is.

**Comment by JeroenVinke** [comment]
Sounds good!

**Comment by JeroenVinke** [comment]
Added the initial implementation to https://github.com/monterey-framework/cli/pull/14. Todo: https://github.com/monterey-framework/cli/issues/19 and https://github.com/monterey-framework/cli/issues/15
