### ISSUE TITLE
sweetalert css import

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/cli#25]
Sweetalert has the following directory structure:

![image](https://cloud.githubusercontent.com/assets/2189477/21498488/35197668-cc2d-11e6-81f3-4e938743c8e1.png)

Sweetalert references [lib/sweetalert.js](https://github.com/t4t5/sweetalert/blob/master/package.json#L5) as the main file in package.json.

The package is configured as follows:

```
{
      "name": "sweetalert",
      "path": "../node_modules/sweetalert/lib",
      "main": "sweetalert"
}
```

Using the following code in `app.js`:

```
import swal from 'sweetalert';

export class App {

	constructor() {
		this.message = 'Hello Sweetalert!';
	}

  attached() {
    swal("hello")
  }
}
```

renders:

![image](https://cloud.githubusercontent.com/assets/2189477/21498569/f9c12416-cc2d-11e6-9074-ff712193b3e5.png)

The css has not been loaded. Since the importer has configured sweetalert with the path as `../node_modules/sweetalert/lib`, it is not possible to load the css file which lives in `../node_modules/sweetalert/dist/`.

A working configuration is:
```
  <require from="sweetalert/dist/sweetalert.css"></require>


          {
            "name": "sweetalert",
            "path": "../node_modules/sweetalert",
            "main": "lib/sweetalert",
            "resources": [
              "dist/sweetalert.css"
            ]
          }
```

Since the package.json of sweetalert does not mention that the css file is in the `dist` folder, the importer doesn't know that sweetalert has a css file. Perhaps we can create a PR to add a `style` property in the package.json of sweetalert ([more info](http://stackoverflow.com/questions/32037150/style-field-in-package-json)). [Bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L35) does this as well.

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/cli/commit/b1a1596e0c951232ec81da849b21943020c75251

**Comment by adriatic** [comment]
> Perhaps we can create a PR to add a style property in the package.json of sweetalert

Yes, very much so - consider ourselves to be on the mission to put some order in the world of packages creation.

**Comment by JeroenVinke** [comment]
Yes, I have done two things. The importer will look for a `style` property in the package.json file now, and it will configure the package appropriately when it finds this property. Now we can submit a PR to sweetalert to add the `style` property to their package.json file.

But in order to support sweetalert right now I have added the correct config to the registry [here](https://github.com/monterey-framework/cli/blob/76377b2b448be64e6898e1a98741a4c28178dcb6/lib/importer/registry/sweetalert/0.0.0.json).
