### ISSUE TITLE
Create amodotrace importer strategy

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/cli#9]
![image](https://cloud.githubusercontent.com/assets/2189477/20866847/6a579ff6-ba37-11e6-8caa-11eb4c59acaf.png)

When everything else fails, we can load the `main` file of the plugin and use amodotrace to determine what dependencies the package has. Using this information we can configure the plugin (not sure how yet). We should configure these packages as CommonJS

**Comment by JeroenVinke** [comment]
> If no browser spec configuration is found, use the standard package main field. Load the main module with amodro trace and see if it has any dependencies. If it does, configure the package as a commonjs package format. If it doesn't use a standard configuration. (I'm not sure if we can do this successfully with amodro. If not, we can just default to a standard configuration).

[Example usage of amodrotrace](https://github.com/monterey-framework/cli/blob/feat/import/lib/build/bundled-source.js#L69-L124)

@EisenbergEffect How can we configure a package as commonjs? [Aurelia](https://github.com/aurelia/bootstrapper/tree/master/dist) exports libraries in different package formats, but most plugins only export in one package format

**Comment by EisenbergEffect** [comment]
Amodro will detect whether or not it is amd or commonjs and make the conversion. Is that what you are asking?

**Comment by JeroenVinke** [comment]
I do not really understand this part:

>  If it does, configure the package as a commonjs package format.

As far as I know we cannot define the package format for a dependency in the aurelia.json file, so I was wondering how we should configure a package as commonjs.

**Comment by EisenbergEffect** [comment]
Oh. Sorry. It's not a matter of commonjs vs. amd actually. Sorry for the confusion. It's a bit difficult to explain. Rather, we need to know that the module is in a "package" style like a node.js module, regardless of the format it is in. An example of this is aurelia-templating-resources and aurelia-templatingr-router vs. aurelia-metadata, for example. Basically, all code in a single file vs. a package of files.

**Comment by JeroenVinke** [comment]
That makes sense, I understand what you mean.
